name: CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - '**/README.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build, publish, and deploy
        run: |
          sudo apt-get update && sudo apt-get upgrade -y
          sudo apt-get install -y sshpass openssh-client
          dotnet publish notebookdb.API -c Release 
          sshpass -p '${{ secrets.SERVERPASSWORD }}' scp -o StrictHostKeyChecking=no -P ${{ secrets.SERVERPORT }} -r ${{ github.workspace }}/notebookdb.API/bin/Release/net9.0/publish/* ${{ secrets.SERVERUSERNAME }}@${{ secrets.SERVERADDRESS }}:/var/www/notebookdb      
          sshpass -p '${{ secrets.SERVERPASSWORD }}' ssh -o StrictHostKeyChecking=no -p ${{ secrets.SERVERPORT }} ${{ secrets.SERVERUSERNAME }}@${{ secrets.SERVERADDRESS }} "sudo systemctl restart kestrel-notebookdb.service"
          sshpass -p '${{ secrets.SERVERPASSWORD }}' ssh -o StrictHostKeyChecking=no -p ${{ secrets.SERVERPORT }} ${{ secrets.SERVERUSERNAME }}@${{ secrets.SERVERADDRESS }} "sudo systemctl restart nginx"
